language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get -y install qt56base
    - sudo apt-get -y install build-essential libasound2-dev liblua5.1-dev libsdl1.2-dev libgl1-mesa-dev wine-dev
    - source /opt/qt*/bin/qt*-env.sh

script:
  - cd build
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - ln -s linuxdeployqt-continuous-x86_64.AppImage linuxdeployqt
  - ./build.sh
  - ./linux-deploy.sh